dist: bionic
language: python
python:
  - "3.7"
install: pip3 install requests==2.20.0 docker-compose
script:
 - docker-compose up --build -d
 - docker-compose ps
 - netstat -nta
 - sleep 5
 - test/test_docker.py
 - cd training
 - docker build -t advdecorr_training .
 - docker run advdecorr_training
