swagger: "2.0"

info:
  version: 1.0.0
  title: API to receive parameters and issue sample classification with NN.
  description: API to receive parameters and issue sample classification with NN.

consumes:
  - application/json

produces:
  - application/json

schemes:
  - https
host: localhost
basePath: /

paths:
  /classify:
    post:
      summary: Classify input data.
      description: Returns the p-value, which indicates how likely a sample comes from signal or background.
      operationId: app.post_classify
      parameters:
        - name: sample
          in: body
          schema:
            $ref: '#/definitions/Sample'
      responses:
        200:
          description: A list of p-values for each sample.
          schema:
            $ref: '#/definitions/Sample'

definitions:
  Sample:
    type: object
    required:
      - i
      - A
      - B
    properties:
      i:
        type: integer
        description: Sample number.
        example: 1
      A:
        type: string
        description: Value of A.
        example: "0"
      B:
        type: string
        description: Value of B.
        example: "0"
      pvalue:
        type: string
        description: p-value.
        example: "0.5"
      tags:
        type: object
        description: Custom tags.
      created:
        type: string
        format: date-time
        description: Creation time.
        readOnly: true
